// <auto-generated />
using System;
using Hospital.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital.DAL.Migrations
{
    [DbContext(typeof(HospitalContext))]
    [Migration("20230609233144_AddingDataForAllEntities")]
    partial class AddingDataForAllEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital.DAL.Data.Models.Doctor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerofrmancRate")
                        .HasColumnType("int");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7c2748f1-542e-481d-ae6f-3540363d25f2"),
                            Name = "Jessie",
                            PerofrmancRate = 65,
                            Salary = 27064m,
                            Specialization = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("dda8c822-2b70-482f-885f-f21c78b09ae0"),
                            Name = "Judy",
                            PerofrmancRate = 32,
                            Salary = 18711m,
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = new Guid("d07b2127-63bf-4a99-a088-1439b7abc716"),
                            Name = "Naomi",
                            PerofrmancRate = 27,
                            Salary = 32145m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("def6ead3-40b8-4a09-8400-7ef4860cc3c6"),
                            Name = "Joann",
                            PerofrmancRate = 72,
                            Salary = 9232m,
                            Specialization = "Hematology"
                        },
                        new
                        {
                            Id = new Guid("962c812c-8b9f-4d0f-adbb-6687598e9686"),
                            Name = "Judy",
                            PerofrmancRate = 19,
                            Salary = 48498m,
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = new Guid("7f4513f5-e94c-4a28-97d3-01d2e7db429a"),
                            Name = "Alyssa",
                            PerofrmancRate = 79,
                            Salary = 16586m,
                            Specialization = "Gastroenterology"
                        },
                        new
                        {
                            Id = new Guid("31263557-9d5f-4122-ae33-80291ebda99b"),
                            Name = "Mable",
                            PerofrmancRate = 5,
                            Salary = 33706m,
                            Specialization = "Infectious Disease"
                        },
                        new
                        {
                            Id = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Paula",
                            PerofrmancRate = 0,
                            Salary = 19094m,
                            Specialization = "Urology"
                        },
                        new
                        {
                            Id = new Guid("4e5e9239-303f-4970-83fa-2c9d96501202"),
                            Name = "Rafael",
                            PerofrmancRate = 97,
                            Salary = 12266m,
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = new Guid("0c9b8333-3133-4d48-a8e1-c1cea7531d28"),
                            Name = "Sara",
                            PerofrmancRate = 82,
                            Salary = 45041m,
                            Specialization = "Pediatrics"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Data.Models.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = new Guid("80763482-7333-4a01-8fd8-f26b7a75f29d"),
                            Name = "Diabetes"
                        },
                        new
                        {
                            Id = new Guid("9875c79c-7402-4339-acd0-af0d35c9cef0"),
                            Name = "Hypertension"
                        },
                        new
                        {
                            Id = new Guid("77c09e5a-6ffb-4f20-ac11-4dcfd75ffa0d"),
                            Name = "Asthma"
                        },
                        new
                        {
                            Id = new Guid("e481cdb1-3997-4293-b901-b42d0b380cc2"),
                            Name = "Depression"
                        },
                        new
                        {
                            Id = new Guid("a1811b24-c18c-491f-af88-cd0aa2fb1f31"),
                            Name = "Arthritis"
                        },
                        new
                        {
                            Id = new Guid("ea8219c4-d796-4503-801f-3c5b1973c84b"),
                            Name = "Allergy"
                        },
                        new
                        {
                            Id = new Guid("e35764c8-0092-453a-93b9-2954399a1e5b"),
                            Name = "Flu"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Data.Models.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DoctorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = new Guid("93b3b5b4-2e47-47f2-ad5a-06df74cf9069"),
                            DoctorId = new Guid("7f4513f5-e94c-4a28-97d3-01d2e7db429a"),
                            Name = "Dana"
                        },
                        new
                        {
                            Id = new Guid("84ac2c2d-5600-4fa1-a526-482c170cac6f"),
                            DoctorId = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Isaac"
                        },
                        new
                        {
                            Id = new Guid("809c8f2f-f7ab-4d21-9a2d-774104ffc690"),
                            DoctorId = new Guid("0c9b8333-3133-4d48-a8e1-c1cea7531d28"),
                            Name = "Damon"
                        },
                        new
                        {
                            Id = new Guid("02d3f64b-8bac-47f6-af01-1772dc601a79"),
                            DoctorId = new Guid("4e5e9239-303f-4970-83fa-2c9d96501202"),
                            Name = "Miriam"
                        },
                        new
                        {
                            Id = new Guid("1f9a04fb-67a6-4ad6-8495-b00bd047a508"),
                            DoctorId = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Terence"
                        },
                        new
                        {
                            Id = new Guid("e31fe1aa-7d41-4975-8af5-d34592497d9f"),
                            DoctorId = new Guid("dda8c822-2b70-482f-885f-f21c78b09ae0"),
                            Name = "Roosevelt"
                        },
                        new
                        {
                            Id = new Guid("31de0090-70e0-4ba4-9312-d6fb14bd7350"),
                            DoctorId = new Guid("0c9b8333-3133-4d48-a8e1-c1cea7531d28"),
                            Name = "Eduardo"
                        },
                        new
                        {
                            Id = new Guid("e2c2bb59-b9a9-4528-89f3-6a4ef07f5651"),
                            DoctorId = new Guid("4e5e9239-303f-4970-83fa-2c9d96501202"),
                            Name = "Wilbert"
                        },
                        new
                        {
                            Id = new Guid("79d60fef-853f-4277-aca3-fe7917477cf2"),
                            DoctorId = new Guid("7f4513f5-e94c-4a28-97d3-01d2e7db429a"),
                            Name = "Tasha"
                        },
                        new
                        {
                            Id = new Guid("27745011-93d9-42d5-adca-db3a8b1c24d3"),
                            DoctorId = new Guid("dda8c822-2b70-482f-885f-f21c78b09ae0"),
                            Name = "Max"
                        },
                        new
                        {
                            Id = new Guid("cad37d55-aaf8-4658-aad9-bc8b433dec56"),
                            DoctorId = new Guid("d07b2127-63bf-4a99-a088-1439b7abc716"),
                            Name = "Bridget"
                        },
                        new
                        {
                            Id = new Guid("ebad9b47-bd97-44d2-b25f-b016fc82d156"),
                            DoctorId = new Guid("4e5e9239-303f-4970-83fa-2c9d96501202"),
                            Name = "Juan"
                        },
                        new
                        {
                            Id = new Guid("339c6c23-5f72-4dac-9798-4a216522067f"),
                            DoctorId = new Guid("7c2748f1-542e-481d-ae6f-3540363d25f2"),
                            Name = "Krystal"
                        },
                        new
                        {
                            Id = new Guid("111eeca8-a8c1-416e-94f4-70d3e3db8274"),
                            DoctorId = new Guid("7c2748f1-542e-481d-ae6f-3540363d25f2"),
                            Name = "Erma"
                        },
                        new
                        {
                            Id = new Guid("ff4fdac0-41fb-4a53-9314-916a99bca50d"),
                            DoctorId = new Guid("31263557-9d5f-4122-ae33-80291ebda99b"),
                            Name = "Orlando"
                        },
                        new
                        {
                            Id = new Guid("ca353e21-906e-4688-bbe2-68211a37f2d8"),
                            DoctorId = new Guid("7f4513f5-e94c-4a28-97d3-01d2e7db429a"),
                            Name = "Marvin"
                        },
                        new
                        {
                            Id = new Guid("abc4274e-cd0f-4ab1-9267-6a579a3cb0ad"),
                            DoctorId = new Guid("962c812c-8b9f-4d0f-adbb-6687598e9686"),
                            Name = "Lamar"
                        },
                        new
                        {
                            Id = new Guid("67482b83-abe9-4284-9745-3b3536eeff52"),
                            DoctorId = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Joe"
                        },
                        new
                        {
                            Id = new Guid("0363e9e8-7496-4016-b812-ea260d15d18e"),
                            DoctorId = new Guid("4e5e9239-303f-4970-83fa-2c9d96501202"),
                            Name = "Wendell"
                        },
                        new
                        {
                            Id = new Guid("9651ab33-11d6-43e9-b3d0-8f7cd610dced"),
                            DoctorId = new Guid("962c812c-8b9f-4d0f-adbb-6687598e9686"),
                            Name = "Sandra"
                        },
                        new
                        {
                            Id = new Guid("6800f603-b1f2-4c79-a7f0-0071b35a4cbf"),
                            DoctorId = new Guid("31263557-9d5f-4122-ae33-80291ebda99b"),
                            Name = "Stephanie"
                        },
                        new
                        {
                            Id = new Guid("c22afc5e-e2dd-40d5-9c43-be7087b25ca4"),
                            DoctorId = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Ervin"
                        },
                        new
                        {
                            Id = new Guid("ed1fd551-0825-43b8-9448-96d4d8db2566"),
                            DoctorId = new Guid("962c812c-8b9f-4d0f-adbb-6687598e9686"),
                            Name = "Beth"
                        },
                        new
                        {
                            Id = new Guid("8f64e8c6-3deb-42c6-82e6-9d7ed61cccf8"),
                            DoctorId = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Gretchen"
                        },
                        new
                        {
                            Id = new Guid("da77d4a4-b1ca-48da-9179-12c3519e7b79"),
                            DoctorId = new Guid("d07b2127-63bf-4a99-a088-1439b7abc716"),
                            Name = "Gwendolyn"
                        },
                        new
                        {
                            Id = new Guid("f0747687-641a-4fa8-bc5e-3698a9fd26f1"),
                            DoctorId = new Guid("d20c0117-f1d6-47fe-847e-e54f5db5d1b2"),
                            Name = "Jerry"
                        },
                        new
                        {
                            Id = new Guid("951a7cb0-d616-48eb-8c43-24283a49063f"),
                            DoctorId = new Guid("31263557-9d5f-4122-ae33-80291ebda99b"),
                            Name = "Mitchell"
                        },
                        new
                        {
                            Id = new Guid("b0ff4256-29f7-4a4a-a588-a4fafbb14efd"),
                            DoctorId = new Guid("4e5e9239-303f-4970-83fa-2c9d96501202"),
                            Name = "Maggie"
                        },
                        new
                        {
                            Id = new Guid("eaeb6e0a-f1c7-490c-bf70-660ba9222e89"),
                            DoctorId = new Guid("def6ead3-40b8-4a09-8400-7ef4860cc3c6"),
                            Name = "Sandy"
                        },
                        new
                        {
                            Id = new Guid("cb5687ef-fb60-4689-ac08-c711cde82aa1"),
                            DoctorId = new Guid("d07b2127-63bf-4a99-a088-1439b7abc716"),
                            Name = "Lloyd"
                        });
                });

            modelBuilder.Entity("Hospital.DAL.Data.Models.Patient", b =>
                {
                    b.HasOne("Hospital.DAL.Data.Models.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });
#pragma warning restore 612, 618
        }
    }
}
